#!/usr/bin/env python3

import colormode
import nocolor
import sys
from configurations import options

def main():
	if options().nocolors:
		sp = nocolor.StatusParserNoColor()
		sp.parser()

	elif not options().nocolors:
		sp = colormode.StatusParserColorMode()
		sp.parser()

if __name__ == "__main__":
	main()
	sys.exit(0)